import subprocess
import os

# Define the LaTeX code with the correct path to the font
latex_code = r"""
\documentclass{article}
\usepackage{fontspec}

% Specify the path to your custom TTF font
\newfontface\customfont[Path=./FontFusion/Fusion1/]{Unconfirmed 831238.ttf}

\begin{document}

% Use the custom font for some text
\customfont
This text is in your custom font.

\end{document}
"""

# Save the LaTeX code to a .tex file
with open('document.tex', 'w') as file:
    file.write(latex_code)

# Ensure your custom TTF font is in the specified directory
font_path = "FontFusion/Fusion1/Unconfirmed 831238.ttf"
if not os.path.exists(font_path):
    print(f"Error: {font_path} not found.")
else:
    # Compile the LaTeX code to PDF using xelatex
    xelatex_path = r'C:\Users\ADMIN\AppData\Local\Programs\MiKTeX\miktex\bin\x64\xelatex.exe'
    result = subprocess.run([xelatex_path, 'document.tex'], capture_output=True, text=True)
    print(result.stdout)
    print(result.stderr)

    # Optional: Clean up auxiliary files generated by xelatex
    for ext in ['aux', 'log']:
        try:
            os.remove(f'document.{ext}')
        except FileNotFoundError:
            pass
